MyBlog/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User,AbstractUser
from tinymce.models import HTMLField
from tinymce import models as tinymce_models
from uuslug import slugify
#


class BlogPostAdmin(admin.ModelAdmin):
    list_display = ("title",'timestamp')
from django.db import models

# Create your models here.
class superuser(AbstractUser):
    # user= models.OneToOneField(User,on_delete=models.CASCADE)
    # username = models.CharField(max_length=500)
    password = models.CharField(max_length=50)
    sighs = models.IntegerField(default=0)
    date = models.IntegerField(default=11)
    cha = models.CharField(max_length=100, default="hllo")
    touxiang = models.FileField(upload_to = 'touxiang/',default="touxiang/5.jpg")



class diary(models.Model):
    diary_txt = tinymce_models.HTMLField(max_length=100, default="hllo")
    title = models.CharField(max_length=100, default="hllo")
    user = models.ForeignKey(superuser,on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    kind = models.CharField(max_length=100, default="hllo")
    slug = models.SlugField(default = 0)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super(diary, self).save(*args, **kwargs)

class comment(models.Model):
    comment = models.CharField(max_length=100, default="hllo")
    user = models.ForeignKey(diary,on_delete=models.CASCADE)

class IMG(models.Model):
    user = models.ForeignKey(superuser,on_delete=models.CASCADE)
    pub_date = models.DateTimeField('date published')
    img = models.FileField(upload_to = 'upload/',null=True,default="touxiang/5.jpg" )

MyBlog/templates/Login.html
<!doctype html>
<html>
   {% load staticfiles %}
<head>
<meta charset="UTF-8">
<title>登陆</title>
<link href={% static "Login.css" %} rel="stylesheet" type="text/css">
<link href={%  static "style.css" %} rel="stylesheet" type="text/css">
<script type="text/javascript">
 //页面淡入淡出
$(document).ready(function() {
$('body').hide().fadeIn(5000);
});
</script>
<script type="text/javascript">
 //页面淡入淡出
$(document).ready(function(){
$("body").css("display","none");
$("body").fadeIn("slow");
$("a[target],a[href*='javascript'],a.lightbox-processed,a[href*='#']").addClass("speciallinks");
$("a:not(.speciallinks)").click(function(){
$("body").fadeOut("slow");
$("object,embed").css("visibility","hidden");
});
});
</script>
<script src={% static "js/jquery-1.8.2.js"%}></script>
</head>
<body>
 <div class="error" >用户名或密码输入错误</div>
	<div class="container">
		<div class="background">
			<form method="post" class="infor">
				<img src={% static "images/username.png"%} alt="" class="img" >
				<input type="text"  name="username" id="a" value="username" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'username';}">
				<img src={% static "images/password.png"%} alt="" id="img" class="img">
				<input type="password" name="password" id= "b" value="11111" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = '11111';}">
				<script>
            		function myFunction()
           			{
            			var x=document.getElementById("a").value;
						var y=document.getElementById("b").value;

            			if(x==""||y=="")
	       				{
	        				alert("Please complete your information");
	         			}
            		}
             	</script>

        		<button type="submit" onclick="myFunction()" class="btn1">登录
        		</button>
		 		<a  href="http://127.0.0.1:8000/online/regist/">
					<button type="button"  class="btn2">
						注册
					</button>
				</a>
			</form>
		</div>
	</div>

</body>

MyBlog/templates/Login2.html
<!doctype html>
<html>
   {% load staticfiles %}
<head>
<meta charset="UTF-8">
<title>登陆</title>
<link href={% static "Login.css" %} rel="stylesheet" type="text/css">
<link href={%  static "style.css" %} rel="stylesheet" type="text/css">
<script type="text/javascript">
 //页面淡入淡出
$(document).ready(function() {
$('body').hide().fadeIn(5000);
});
</script>
<script type="text/javascript">
 //页面淡入淡出
$(document).ready(function(){
$("body").css("display","none");
$("body").fadeIn("slow");
$("a[target],a[href*='javascript'],a.lightbox-processed,a[href*='#']").addClass("speciallinks");
$("a:not(.speciallinks)").click(function(){
$("body").fadeOut("slow");
$("object,embed").css("visibility","hidden");
});
});
</script>
<script src={% static "js/jquery-1.8.2.js"%}></script>
</head>
<body>

	<div class="container">
		<div class="background">
			<form method="post" class="infor">
				<img src={% static "images/username.png"%} alt="" class="img" >
				<input type="text"  name="username" id="a" value="username" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = 'username';}">
				<img src={% static "images/password.png"%} alt="" id="img" class="img">
				<input type="password" name="password" id= "b" value="11111" onFocus="this.value = '';" onBlur="if (this.value == '') {this.value = '11111';}">
				<script>
            		function myFunction()
           			{
            			var x=document.getElementById("a").value;
						var y=document.getElementById("b").value;
		
            			if(x==""||y=="")
	       				{
	        				alert("Please complete your information");
	         			}
            		}
             	</script>

        		<button type="submit" onclick="myFunction()" class="btn1">登录
        		</button>
		 		<a  href="http://127.0.0.1:8000/online/regist/">
					<button type="button"  class="btn2">
						注册
					</button>
				</a>
			</form>
		</div>
	</div>

</body>

MyBlog/templates/base_site.html
{% extends "admin/base.html" %}

{% block title %}{{ title }} | {{ site_title|default:_('Django site admin') }}{% endblock %}

{% block branding %}
<h1 id="site-name"><a href="{% url 'admin:index' %}">{{ site_header|default:_('Django') }}</a></h1>
{% endblock %}

{% block nav-global %}{% endblock %}

MyBlog/templates/memory1.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">


	<title>音乐类</title>
	<link type="text/css"  rel="stylesheet" href= "{% static "part-1.css" %}">
    <style type="text/css">
        .href1{
              font-size:0.6em ;
        }
        .href2{
              font-size:0.6em ;
              position: relative;
              top: -58px;
              left:20%
        }
        .href3{
              font-size:0.6em ;
              position: relative;
              top: -120px;
              left:20%
        }
        .submit{
             font-size:0.6em ;
              position: relative;
              top: -110px;
              left:34%

        }
    </style >
</head>

<body>

<!-- 导航栏及页首-->

<script src={% static "tiny_mce/tiny_mce.js"%}></script>
<script>
    tinyMCE.init({
        'mode':'textareas',
        'width':550,
        'height':300
    })
</script>

	<div class="header">
		<h1> 学习类</h1>
	</div>
	<div class="bg" >
		<div class="container">
			<img class="pic1" src={% static "images/2.jpg"%} />
			<img class="pic2" src={% static "images/3.jpg"%} />
			<img src={% static "images/4.jpg" %} class="pic3" />
			<ul class="list">
				{% for a in latest_diary_list %}
{{ a.id }}
                   {{a.pub_date}}
                    <br>
                   标题： {{ a.title }}

                    <p>{{a.diary_txt}}</p>
                    <p>评论:</p>
                    {% for b in a.comment_set.all %}
                        <p>{{ b.comment}}</p>

                        {% endfor %}

         <!--文本编辑栏修改-->
    <div class="modal fade" id= '{{ a.id }}1'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">修改</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/change/" enctype="multipart/form-data">

                            <textarea name="a" style="width: 100%;height: 500px;font-size: 200%">
                          {{ a.diary_txt }}
                             </textarea >
                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="1">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

      <div class="modal fade" id= '{{ a.id }}'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">评论</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/comment/" enctype="multipart/form-data">
		        			<!--文本内容-->
							<textarea name="a" style="width: 100%;height: 500px;font-size: 200%">

                             </textarea >


                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="1">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

       <div >
		            <a class = "href1" href='#{{ a.id }}1' data-toggle="modal">修改</a>
                    </div>
                    <div >
		            <a class = "href2" href='#{{ a.id }}' data-toggle="modal">评论</a>
                    </div>
                     <form method="POST" action= "http://127.0.0.1:8000/online/delete/" >
		        			<!--文本内容-->
                         <input type="hidden" name="id" value={{ a.id }}>
                         <input class = "submit" type="submit" value="删除" >
                         <input type="hidden" name="type" value="1">
                        </form>
                    <a class = "href3" href='http://127.0.0.1:8000/online/detail/{{ a.slug }}/' data-toggle="modal">详情</a>
                    {% endfor %}
			</ul>
    	</div>
    </div>

<!--文本编辑栏-->







	<script src="../bootstrap/bootstrap-3.3.7-dist/js/jquery-3.2.1.js"></script>
	<script src="{% static 'bootstrap.js' %}" ></script>
	<script type="text/javascript" src="{% static 'Recorder.js' %}" ></script>
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

MyBlog/templates/memory2.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">


	<title>学习类</title>
	<link type="text/css"  rel="stylesheet" href= "{% static "part-1.css" %}">
    <style type="text/css">
        .href1{
              font-size:0.6em ;
        }
        .href2{
              font-size:0.6em ;
              position: relative;
              top: -58px;
              left:20%
        }
        .href3{
              font-size:0.6em ;
              position: relative;
              top: -120px;
              left:20%
        }
        .submit{
             font-size:0.6em ;
              position: relative;
              top: -110px;
              left:34%

        }
    </style >
</head>

<body>

<!-- 导航栏及页首-->

<script src={% static "tiny_mce/tiny_mce.js"%}></script>
<script>
    tinyMCE.init({
        'mode':'textareas',
        'width':550,
        'height':300
    })
</script>

	<div class="header">
		<h1> 学习类</h1>
	</div>
	<div class="bg" >
		<div class="container">
			<img class="pic1" src={% static "images/2.jpg"%} />
			<img class="pic2" src={% static "images/3.jpg"%} />
			<img src={% static "images/4.jpg" %} class="pic3" />
			<ul class="list">
				{% for a in latest_diary_list %}
{{ a.id }}
                   {{a.pub_date}}
                    <br>
                   标题： {{ a.title }}

                    <p>{{a.diary_txt}}</p>
                    <p>评论:</p>
                    {% for b in a.comment_set.all %}
                        <p>{{ b.comment}}</p>

                        {% endfor %}

         <!--文本编辑栏修改-->
    <div class="modal fade" id= '{{ a.id }}1'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">修改</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/change/" enctype="multipart/form-data">

                            <textarea name="a" style="width: 100%;height: 500px;font-size: 200%">
                          {{ a.diary_txt }}
                             </textarea >
                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="2">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

      <div class="modal fade" id= '{{ a.id }}'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">评论</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/comment/" enctype="multipart/form-data">
		        			<!--文本内容-->
							<textarea name="a" style="width: 100%;height: 500px;font-size: 200%">

                             </textarea >


                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="2">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

       <div >
		            <a class = "href1" href='#{{ a.id }}1' data-toggle="modal">修改</a>
                    </div>
                    <div >
		            <a class = "href2" href='#{{ a.id }}' data-toggle="modal">评论</a>
                    </div>
                     <form method="POST" action= "http://127.0.0.1:8000/online/delete/" >
		        			<!--文本内容-->
                         <input type="hidden" name="id" value={{ a.id }}>
                         <input class = "submit" type="submit" value="删除" >
                         <input type="hidden" name="type" value="2">
                        </form>
                    <a class = "href3" href='http://127.0.0.1:8000/online/detail/{{ a.slug }}/' data-toggle="modal">详情</a>
                    {% endfor %}
			</ul>
    	</div>
    </div>

<!--文本编辑栏-->







	<script src="../bootstrap/bootstrap-3.3.7-dist/js/jquery-3.2.1.js"></script>
	<script src="{% static 'bootstrap.js' %}" ></script>
	<script type="text/javascript" src="{% static 'Recorder.js' %}" ></script>
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

MyBlog/templates/memory3.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">


	<title>人际关系类</title>
	<link type="text/css"  rel="stylesheet" href= "{% static "part-1.css" %}">
    <style type="text/css">
        .href1{
              font-size:0.6em ;
        }
        .href2{
              font-size:0.6em ;
              position: relative;
              top: -58px;
              left:20%
        }
        .href3{
              font-size:0.6em ;
              position: relative;
              top: -120px;
              left:20%
        }
        .submit{
             font-size:0.6em ;
              position: relative;
              top: -110px;
              left:34%

        }
    </style >
</head>

<body>

<!-- 导航栏及页首-->

<script src={% static "tiny_mce/tiny_mce.js"%}></script>
<script>
    tinyMCE.init({
        'mode':'textareas',
        'width':550,
        'height':300
    })
</script>

	<div class="header">
		<h1> 人际关系类</h1>
	</div>
	<div class="bg" >
		<div class="container">
			<img class="pic1" src={% static "images/2.jpg"%} />
			<img class="pic2" src={% static "images/3.jpg"%} />
			<img src={% static "images/4.jpg" %} class="pic3" />
			<ul class="list">
				{% for a in latest_diary_list %}
{{ a.id }}
                   {{a.pub_date}}
                    <br>
                   标题： {{ a.title }}

                    <p>{{a.diary_txt}}</p>
                    <p>评论:</p>
                    {% for b in a.comment_set.all %}
                        <p>{{ b.comment}}</p>

                        {% endfor %}

         <!--文本编辑栏修改-->
    <div class="modal fade" id= '{{ a.id }}1'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">修改</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/change/" enctype="multipart/form-data">

                            <textarea name="a" style="width: 100%;height: 500px;font-size: 200%">
                          {{ a.diary_txt }}
                             </textarea >
                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="3">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

      <div class="modal fade" id= '{{ a.id }}'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">评论</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/comment/" enctype="multipart/form-data">
		        			<!--文本内容-->
							<textarea name="a" style="width: 100%;height: 500px;font-size: 200%">

                             </textarea >


                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="3">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

       <div >
		            <a class = "href1" href='#{{ a.id }}1' data-toggle="modal">修改</a>
                    </div>
                    <div >
		            <a class = "href2" href='#{{ a.id }}' data-toggle="modal">评论</a>
                    </div>
                     <form method="POST" action= "http://127.0.0.1:8000/online/delete/" >
		        			<!--文本内容-->
                         <input type="hidden" name="id" value={{ a.id }}>
                         <input class = "submit" type="submit" value="删除" >
                         <input type="hidden" name="type" value="3">
                        </form>
                    <a class = "href3" href='http://127.0.0.1:8000/online/detail/{{ a.slug }}/' data-toggle="modal">详情</a>
                    {% endfor %}
			</ul>
    	</div>
    </div>

<!--文本编辑栏-->







	<script src="../bootstrap/bootstrap-3.3.7-dist/js/jquery-3.2.1.js"></script>
	<script src="{% static 'bootstrap.js' %}" ></script>
	<script type="text/javascript" src="{% static 'Recorder.js' %}" ></script>
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>

MyBlog/templates/memory4.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
	<meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.css' %}">


	<title>其他类</title>
	<link type="text/css"  rel="stylesheet" href= "{% static "part-1.css" %}">
    <style type="text/css">
        .href1{
              font-size:0.6em ;
        }
        .href2{
              font-size:0.6em ;
              position: relative;
              top: -58px;
              left:20%
        }
        .href3{
              font-size:0.6em ;
              position: relative;
              top: -120px;
              left:20%
        }
        .submit{
             font-size:0.6em ;
              position: relative;
              top: -110px;
              left:34%

        }
    </style >
</head>

<body>

<!-- 导航栏及页首-->

<script src={% static "tiny_mce/tiny_mce.js"%}></script>
<script>
    tinyMCE.init({
        'mode':'textareas',
        'width':550,
        'height':300
    })
</script>

	<div class="header">
		<h1> 其他类</h1>
	</div>
	<div class="bg" >
		<div class="container">
			<img class="pic1" src={% static "images/2.jpg"%} />
			<img class="pic2" src={% static "images/3.jpg"%} />
			<img src={% static "images/4.jpg" %} class="pic3" />
			<ul class="list">
				{% for a in latest_diary_list %}
{{ a.id }}
                   {{a.pub_date}}
                    <br>
                   标题： {{ a.title }}

                    <p>{{a.diary_txt}}</p>
                    <p>评论:</p>
                    {% for b in a.comment_set.all %}
                        <p>{{ b.comment}}</p>

                        {% endfor %}

         <!--文本编辑栏修改-->
    <div class="modal fade" id= '{{ a.id }}1'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">修改</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/change/" enctype="multipart/form-data">

                            <textarea name="a" style="width: 100%;height: 500px;font-size: 200%">
                          {{ a.diary_txt }}
                             </textarea >
                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="4">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

      <div class="modal fade" id= '{{ a.id }}'  tabindex="-1" role="dialog" aria-labelledby="myModalLabel" >
	  	<div class="modal-dialog" role="document">
	    	<div class="modal-content">
	      		<div class="modal-header">
		       	 	<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
		       		<h4 class="modal-title" id="myModalLabel">评论</h4>
	      		</div>
		      	<div class="modal-body" >
		        	<div>
		        		<!--表单-->
		        		<form method="POST" action= "http://127.0.0.1:8000/online/comment/" enctype="multipart/form-data">
		        			<!--文本内容-->
							<textarea name="a" style="width: 100%;height: 500px;font-size: 200%">

                             </textarea >


                            <input type="hidden" name="id" value={{ a.id }}>

                            <input type="hidden" name="type" value="4">

							<input type="submit" value="完成" style="position: absolute;top: 102.3%;left: 90%;z-index: 5000;opacity: 0" >

                        </form>
					</div>
				</div>

			    <div class="modal-footer">
			       <button type="button" class="btn btn-default" data-dismiss="modal">关闭</button>
			       <button type="button" class="btn btn-primary">保存</button>
			    </div>
	    	</div>
	  	</div>
	</div>

       <div >
		            <a class = "href1" href='#{{ a.id }}1' data-toggle="modal">修改</a>
                    </div>
                    <div >
		            <a class = "href2" href='#{{ a.id }}' data-toggle="modal">评论</a>
                    </div>
                     <form method="POST" action= "http://127.0.0.1:8000/online/delete/" >
		        			<!--文本内容-->
                         <input type="hidden" name="id" value={{ a.id }}>
                         <input class = "submit" type="submit" value="删除" >
                         <input type="hidden" name="type" value="4">
                        </form>
                    <a class = "href3" href='http://127.0.0.1:8000/online/detail/{{ a.slug }}/' data-toggle="modal">详情</a>
                    {% endfor %}
			</ul>
    	</div>
    </div>

<!--文本编辑栏-->







	<script src="../bootstrap/bootstrap-3.3.7-dist/js/jquery-3.2.1.js"></script>
	<script src="{% static 'bootstrap.js' %}" ></script>
	<script type="text/javascript" src="{% static 'Recorder.js' %}" ></script>
	<script src="http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js"></script>
	<script src="http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>